apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-doctor
  namespace: testing-project1
spec:
  selector:
      matchLabels:
        app: testing-doctor
  replicas: 1
  template:
    metadata:
      labels:
        app: testing-doctor
    spec:
      containers:         
        - name: testing-doctor
          image: 'neethirocks/testing-doctor:1.1'          
          ports:
            - containerPort: 8080
          env:
          - name: spring_jpa_database
            value: mysql
          - name: spring_datasource_url
            value: jdbc:mysql://healthdb:3306/test?createDatabaseIfNotExist=true&useSSL=false
          - name: spring_datasource_username
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
          - name: spring_datasource_password
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: testing-doctor-service
  labels:
    name: testing-doctor-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: '8080'
      nodePort: 31846
  selector:
    app: testing-doctor
  type: NodePort
