apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthdb
  namespace: testing-project1
spec:
  selector:
    matchLabels:
      app: healthdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: healthdb
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_SERVER_CONTAINER
          value: mysql
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
          name: healthdb
---
apiVersion: v1
kind: Service
metadata:
  name: healthdb
spec:
  type: NodePort
  ports:
  - name: healthdb
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: healthdb
