---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: testing-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/testingdataDR"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testing-pv-claim
  labels:
   app: testing-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testinghealthdb
  namespace: testing-project1
spec:
  selector:
    matchLabels:
      app: testinghealthdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: testinghealthdb
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_SERVER_CONTAINER
          value: mysql
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
          name: testinghealthdb
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: testing-pv-claim
          
---
apiVersion: v1
kind: Service
metadata:
  name: testinghealthdb
spec:
  type: NodePort
  ports:
  - name: testinghealthdb
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: testinghealthdb
